/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by VitePWA (injected at build time)
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// ---------------------------------------------------------------------------
// Runtime caching (mirrors workbox config from vite.config.ts)
// ---------------------------------------------------------------------------

registerRoute(
  ({ url }) => url.origin === 'https://api.stripe.com',
  new NetworkFirst({
    cacheName: 'stripe-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 86400 })],
  })
);

registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 31536000 })],
  })
);

registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 31536000 })],
  })
);

registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 2592000 })],
  })
);

// ---------------------------------------------------------------------------
// Web Push — show notification when a push arrives
// ---------------------------------------------------------------------------

self.addEventListener('push', (event: PushEvent) => {
  const data = event.data ? event.data.json() : {};
  const title: string = data.title || 'LaserHub';
  const options: NotificationOptions & { vibrate?: number[] } = {
    body: data.body || '',
    icon: '/vite.svg',
    badge: '/vite.svg',
    data: { url: data.url || '/' },
    vibrate: [200, 100, 200],
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

// Open the relevant page when the user clicks on a notification
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  // The backend sends `url` as a relative path (e.g. "/orders/123"). Resolve it
  // against the SW scope origin so we can compare against absolute client URLs.
  const rawUrl: string = event.notification.data?.url || '/';
  const targetUrl = new URL(rawUrl, self.location.origin);

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Prefer focusing an already-open tab. Match on path (ignoring origin
        // quirks) and, when possible, navigate it to the exact target.
        for (const client of clientList) {
          const clientUrl = new URL(client.url);
          if (clientUrl.origin === targetUrl.origin && 'focus' in client) {
            if (clientUrl.pathname !== targetUrl.pathname && 'navigate' in client) {
              return (client as WindowClient).navigate(targetUrl.href).then((c) =>
                c ? c.focus() : client.focus()
              );
            }
            return client.focus();
          }
        }
        // Otherwise open a new window at the target URL.
        if (self.clients.openWindow) {
          return self.clients.openWindow(targetUrl.href);
        }
      })
  );
});
